/control/verbose 1
/tracking/verbose 0
#
/LiGen/phys/verbose 0
#
/LiGen/det/z_min 0 m
/LiGen/det/z_max 1500 m
/LiGen/det/rho 2000 m
#
/gps/particle e-
/gps/energy 1 GeV
/gps/position 0 0 0 m
/gps/pos/type Volume
/gps/pos/shape Cylinder
/gps/pos/centre 0 0 300 m
/gps/pos/radius 2000 m
/gps/pos/halfz 250 m
/gps/ang/type iso
#
/LiGen/output/store_photons 1
/LiGen/output/store_histos 0
/LiGen/output/photon_suppression_factor 1
#
/run/initialize
#
/run/printProgress 10
/run/beamOn 200
